name: Core

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    tags: [ v* ]
  pull_request:
  merge_group:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_BASEDIR: "${{ github.workspace }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Send telegram tips
        run: |
          count=$(( $(git rev-list --count origin/dev) + 4200 ))
          echo "New version building: $count" > /home/runner/message.txt
          echo -n "新版本构建中：$count" >> /home/runner/message.txt
          message=$(cat /home/runner/message.txt)
          messageid=$(curl -s -X POST -F "chat_id=${{ secrets.CHAT_ID }}" -F "message_thread_id=${{ secrets.MESSAGE_THREAD_ID }}" -F "text=$message" "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" -o- | jq -r '.result.message_id')
          echo "MESSAGE_ID=$messageid" >> $GITHUB_ENV

      - name: Write key
        if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/dev' ) || github.ref_type == 'tag' }}
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
            echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
            echo androidKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
            echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
            echo androidStoreFile='key.jks' >> gradle.properties
            echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks
          fi

      - name: Write random data to machikado&mazoku
        run: |
          dd if=/dev/random of=./magisk-loader/magisk_module/mechikado.arm bs=96 count=1
          dd if=/dev/random of=./magisk-loader/magisk_module/mechikado.arm64 bs=96 count=1
          dd if=/dev/random of=./magisk-loader/magisk_module/mechikado.x64 bs=96 count=1
          dd if=/dev/random of=./magisk-loader/magisk_module/mechikado.x86 bs=96 count=1
          dd if=/dev/random of=./magisk-loader/magisk_module/mechikado.riscv64 bs=96 count=1
          dd if=/dev/random of=./magisk-loader/magisk_module/mezoku bs=96 count=1

      - name: Early bin&lib
        run: |
          mkdir ./magisk-loader/magisk_module/bin
          mkdir ./magisk-loader/magisk_module/lib

      - name: Add fake riscv64 support
        run: |
          mkdir ./magisk-loader/magisk_module/bin/riscv64
          mkdir ./magisk-loader/magisk_module/lib/riscv64
          dd if=/dev/random bs=16600 count=1 of=./magisk-loader/magisk_module/bin/riscv64/dex2oat
          dd if=/dev/random bs=186880 count=1 of=./magisk-loader/magisk_module/lib/riscv64/liblspd.so

      - name: Add fake libpreload
        run: |
          mkdir ./magisk-loader/magisk_module/lib/arm64-v8a
          mkdir ./magisk-loader/magisk_module/lib/armeabi-v7a
          mkdir ./magisk-loader/magisk_module/lib/x86
          mkdir ./magisk-loader/magisk_module/lib/x86_64
          dd if=/dev/random bs=5584 count=1 of=./magisk-loader/magisk_module/lib/arm64-v8a/libpreload.so
          dd if=/dev/random bs=3804 count=1 of=./magisk-loader/magisk_module/lib/armeabi-v7a/libpreload.so
          dd if=/dev/random bs=5752 count=1 of=./magisk-loader/magisk_module/lib/riscv64/libpreload.so
          dd if=/dev/random bs=4716 count=1 of=./magisk-loader/magisk_module/lib/x86/libpreload.so
          dd if=/dev/random bs=5568 count=1 of=./magisk-loader/magisk_module/lib/x86_64/libpreload.so

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: 'false'
          packages: ''

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
            max-size: 2G
            key: ${{ runner.os }}
            restore-keys: ${{ runner.os }}
            save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.12.1

      - name: Remove Android's cmake
        shell: bash
        run: rm -rf $ANDROID_HOME/cmake

      - name: Configure Gradle properties
        run: |
          echo 'org.gradle.caching=true' >> ~/.gradle/gradle.properties
          echo 'org.gradle.parallel=true' >> ~/.gradle/gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC' >> ~/.gradle/gradle.properties
          echo 'android.native.buildOutput=verbose' >> ~/.gradle/gradle.properties

      - name: Build with Gradle
        run: |
          ./gradlew zipAll

      - name: Remove telegram tips
        if: always()
        run: |
          curl -s -X POST -F "chat_id=${{ secrets.CHAT_ID }}" -F "message_id=${{ env.MESSAGE_ID }}" "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/deleteMessage" >> /dev/null

      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          zygiskReleaseName=`ls magisk-loader/release/LSPosed-v*-release.zip | awk -F '(/|.zip)' '{print $3}'` && echo "zygiskReleaseName=$zygiskReleaseName" >> $GITHUB_OUTPUT
          zygiskDebugName=`ls magisk-loader/release/LSPosed-v*-log.zip | awk -F '(/|.zip)' '{print $3}'` && echo "zygiskDebugName=$zygiskDebugName" >> $GITHUB_OUTPUT
          unzip magisk-loader/release/LSPosed-v*-release.zip -d LSPosed-release
          unzip magisk-loader/release/LSPosed-v*-log.zip -d LSPosed-debug

      - name: Upload zygisk release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepareArtifact.outputs.zygiskReleaseName }}
          path: "./LSPosed-release/*"

      - name: Upload zygisk debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepareArtifact.outputs.zygiskDebugName }}
          path: "./LSPosed-debug/*"

      - name: Upload to KV
        if: success()
        run: |
          curl -X POST -H "x-token: ${{ secrets.BOT_TOKEN }}" -H "x-filename: $(basename $(ls magisk-loader/release/LSPosed-v*-release.zip))" --data-binary @$(ls magisk-loader/release/LSPosed-v*-release.zip) https://${{ secrets.BOT_WORKER}}/uploadRelease
          curl -X POST -H "x-token: ${{ secrets.BOT_TOKEN }}" -H "x-filename: $(basename $(ls magisk-loader/release/LSPosed-v*-log.zip))" --data-binary @$(ls magisk-loader/release/LSPosed-v*-log.zip) https://${{ secrets.BOT_WORKER}}/uploadDebug

      - name: Upload to Telegram
        if: success()
        run: |
          versionCode=$(basename $(ls magisk-loader/release/LSPosed-v*-release.zip) | cut -d'-' -f5)
          echo "New version pushed: $versionCode" > /home/runner/message.txt
          echo -n "新版本已推送：$versionCode" >> /home/runner/message.txt
          message=$(cat /home/runner/message.txt)
          curl -s -X POST -H "Content-Type: application/json" -d '{"chat_id": "${{ secrets.CHAT_ID }}", "message_thread_id": "${{ secrets.MESSAGE_THREAD_ID }}", "text": "'"$message"'", "reply_markup": {"inline_keyboard": [[{"text": "Download / 下载", "url": "https://t.me/${{ secrets.BOT_NAME }}?start=dl"}]]}}' "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" >> /dev/null
