name: Patch debug

on:
  workflow_dispatch:
    inputs:
      chat_id:
        description: 'Chat ID'
        required: true
      github_id:
        description: 'GitHub ID'
        required: true
      message_id:
        description: 'Message ID'
        required: true

jobs:
  process-download:
    runs-on: ubuntu-latest
    steps:
    - name: Send uploading tips
      run: |
        curl -s -X POST -H "Content-Type: application/json" -d "{\"chat_id\":\"${{ inputs.chat_id }}\",\"text\":\"uploading...\\n上传中...\",\"reply_to_message_id\":${{ inputs.message_id }}}" "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage"

    - name: Download file
      run: |
        curl -OJ "https://${{ secrets.BOT_WORKER }}/downloadDebugPackage?token=${{ secrets.BOT_TOKEN }}"

    - name: Unzip the file
      run: |
        unzip $(ls ./LSPosed-v*-release-log.zip) -d LSPosed-unpacked

    - name: Make mazako & Replace UserName
      run: |
        cd LSPosed-unpacked
        echo -n "${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}" | openssl enc -aes-256-ecb -a -K $(echo -n "${{ secrets.KEY_STORE_PASSWORD }}" | sha256sum | cut -d' ' -f1) | base64 -d | tail -c 96 > mazako
        sha256sum mazako | awk '{print $1}' > mazako.sha256
        USERNAME=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/user/${{ inputs.github_id }}" | jq -r '.login')
        sed -i "2s/LSPosedDevelopers/$USERNAME/" module.prop
        sed -i "8s/0/${{ inputs.github_id }}/" module.prop
        sha256sum module.prop | awk '{print $1}' > module.prop.sha256
        zip -r ./../LSPosed.zip ./*
        cd ..

    - name: Build zakosign
      run: |
        git clone https://github.com/Lama3L9R/zakosign.git --depth=1
        cd zakosign
        echo '#include <openssl/x509v3.h>' | cat - src/cli.c > temp && mv temp src/cli.c
        make
        mv ./bin/zakosign ./../sukizakosign
        cd ..

    - name: Sign with zakosign
      run: |
        echo -n ${{ secrets.ZAKOSIGN_PEM }} | base64 -d > key.pem
        echo -n ${{ secrets.ZAKOSIGN_CRT }} | base64 -d > key.crt
        chmod +x sukizakosign
        FILENAME=$(ls ./LSPosed-v*-release-log.zip)
        rm $FILENAME
        ./sukizakosign sign ./LSPosed.zip --key key.pem --output $FILENAME --certificate key.crt --force

    - name: Send file via Telegram
      if: success()
      run: |
        curl -F document=@"$(ls ./LSPosed-v*-release-log.zip)" "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendDocument?chat_id=${{ inputs.chat_id }}"
