name: Patch release

on:
  workflow_dispatch:
    inputs:
      chat_id:
        description: 'Chat ID'
        required: true
      github_id:
        description: 'GitHub ID'
        required: true
      message_id:
        description: 'Message ID'
        required: true
      bot_message_id:
        description: 'Bot Message ID'
        required: true

jobs:
  process-download:
    runs-on: ubuntu-latest
    steps:
    - name: Print GitHub ID & Chat ID
      run: |
        echo "Chat ID is: ${{ inputs.chat_id }}"
        echo "GitHub ID is: ${{ inputs.github_id }}"

    - name: Download file
      run: |
        curl -OJ "https://${{ secrets.BOT_WORKER }}/downloadReleasePackage?token=${{ secrets.BOT_TOKEN }}"

    - name: Unzip the file
      run: |
        unzip $(ls ./LSPosed-v*-release.zip) -d LSPosed-unpacked

    - name: Make mazako & Replace UserName
      run: |
        cd LSPosed-unpacked
        ALOTOFID="${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}${{ inputs.github_id }}"
        echo -n "$ALOTOFID" | openssl enc -aes-256-ecb -a -K $(echo -n "${{ secrets.KEY_STORE_PASSWORD }}" | sha256sum | cut -d' ' -f1) | base64 -d | tail -c 96 > mazako
        touch -m -t '198002010000.00' mazako
        sha256sum mazako | awk '{printf "%s",$1}' > mazako.sha256
        touch -m -t '198002010000.00' mazako.sha256
        echo "${{ secrets.KEY_PASSWORD }}" | openssl enc -aes-256-cbc -a -pbkdf2 -pass pass:${{ secrets.KEY_STORE_PASSWORD }} | sed 's/^Salted__//' > machizako.arm
        touch -m -t '198002010000.00' machizako.arm
        sha256sum machizako.arm | awk '{printf "%s",$1}' > machizako.arm.sha256
        touch -m -t '198002010000.00' machizako.arm.sha256
        echo "${{ secrets.KEY_PASSWORD }}" | openssl enc -aes-256-cbc -a -pbkdf2 -pass pass:${{ secrets.KEY_STORE_PASSWORD }} | sed 's/^Salted__//' > machizako.arm64
        touch -m -t '198002010000.00' machizako.arm64
        sha256sum machizako.arm64 | awk '{printf "%s",$1}' > machizako.arm64.sha256
        touch -m -t '198002010000.00' machizako.arm64.sha256
        echo "${{ secrets.KEY_PASSWORD }}" | openssl enc -aes-256-cbc -a -pbkdf2 -pass pass:${{ secrets.KEY_STORE_PASSWORD }} | sed 's/^Salted__//' > machizako.riscv64
        touch -m -t '198002010000.00' machizako.riscv64
        sha256sum machizako.riscv64 | awk '{printf "%s",$1}' > machizako.riscv64.sha256
        touch -m -t '198002010000.00' machizako.riscv64.sha256
        echo "${{ secrets.KEY_PASSWORD }}" | openssl enc -aes-256-cbc -a -pbkdf2 -pass pass:${{ secrets.KEY_STORE_PASSWORD }} | sed 's/^Salted__//' > machizako.x64
        touch -m -t '198002010000.00' machizako.x64
        sha256sum machizako.x64 | awk '{printf "%s",$1}' > machizako.x64.sha256
        touch -m -t '198002010000.00' machizako.x64.sha256
        echo "${{ secrets.KEY_PASSWORD }}" | openssl enc -aes-256-cbc -a -pbkdf2 -pass pass:${{ secrets.KEY_STORE_PASSWORD }} | sed 's/^Salted__//' > machizako.x86
        touch -m -t '198002010000.00' machizako.x86
        sha256sum machizako.x86 | awk '{printf "%s",$1}' > machizako.x86.sha256
        touch -m -t '198002010000.00' machizako.x86.sha256
        USERNAME=$(curl -s -f -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/user/${{ inputs.github_id }}" | jq -r '.login' || echo LSPosedDevelopers)
        sed -i "2s/LSPosedDevelopers/$USERNAME/" module.prop
        sed -i "8s/0/${{ inputs.github_id }}/" module.prop
        sed -i "7s/1145141919810/$(echo 8$(printf '%018d' $(echo "ibase=16;$(echo -n "${{ inputs.github_id }}" | openssl dgst -sha256 -hmac "${{ secrets.KEY_STORE_PASSWORD }}" -hex | cut -d' ' -f2 | tr '[:lower:]' '[:upper:]')%DE0B6B3A7640000" | bc )))/" module.prop
        touch -m -t '198002010000.00' module.prop
        sha256sum module.prop | awk '{printf "%s",$1}' > module.prop.sha256
        touch -m -t '198002010000.00' module.prop.sha256
        zip -r ./../LSPosed.zip ./*
        cd ..

    - name: Build zakosign
      run: |
        git clone https://github.com/Lama3L9R/zakosign.git --depth=1
        cd zakosign
        echo '#include <openssl/x509v3.h>' | cat - src/cli.c > temp && mv temp src/cli.c
        make
        mv ./bin/zakosign ./../sukizakosign
        cd ..

    - name: Sign with zakosign
      run: |
        echo -n ${{ secrets.ZAKOSIGN_PEM }} | base64 -d > key.pem
        echo -n ${{ secrets.ZAKOSIGN_CRT }} | base64 -d > key.crt
        chmod +x sukizakosign
        FILENAME=$(ls ./LSPosed-v*-release.zip)
        rm $FILENAME
        ./sukizakosign sign ./LSPosed.zip --key key.pem --output $FILENAME

    - name: Send uploading tips
      run: |
        curl -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/editMessageText" -F "chat_id=${{ inputs.chat_id }}" -F "message_id=${{ inputs.bot_message_id }}" -F "text=$(printf "uploading...\n上传中...")"

    - name: Send file via Telegram
      if: success()
      run: |
        curl -F document=@"$(ls ./LSPosed-v*-release.zip)" "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendDocument?chat_id=${{ inputs.chat_id }}" >> /dev/null
